### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by CodedNil** [CodedNil/CineMatic#1]
Radarr api
- [x] Search for movies
- [x] Basic interactions and replies
- [x] Add movies, verify with user first
- [x] Get basic movie status, if exists on the server, size etc
- [x] Read and set resolution profiles
- [x] Delete movies
- [x] #25
- [x] Mini ai data processor for lookups, pushes a query, manually write out results into plain english then feed to gpt3.5
- [x] #18
- [x] How would multiple chats work? If server asks something to user?
- [ ] #17

Sonarr api
- [x] Sonarr api basics
- [x] Sonarr add series
- [ ] Delete series
- [ ] Admin required to delete series else cannot call api
- [x] Change series resolution
- [ ] #19
- [ ] Sonarr file sizes

Memories api that stores and retrieves memories
- [x] Basic api with storing file
- [x] Robust memory retrieval
- [x] Robust memory saving, space efficient
- [x] Use memories to create a user recommendations of media to watch etc
- [x] #20
- [ ] #22

Deluge api
- [x] #21

Autonomous actions
- [ ] #23
- [x] #24

Overhaul
- [ ] Remove sonarr and radarr, directly scan filesystem
- [ ] Needs custom resolution request that gets used in finding the files, store this as a file?
- [ ] Custom replacement for prowlarr, or use prowlarr to scan torrent sites
- [ ] Submit torrents to deluge, monitor them and add files
- [ ] Custom "is media on" to handle it being requested but not downloaded
- [ ] Custom tmdb api lookups
- [ ] Custom file data info
